/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e235714;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WarriorTest {
    @Test
    void attackTest() {
        int defaultWarriorattack = 100;
        int defaultslimeHP = 10000;
        Warrior demoWarrior = new Warrior("デモ戦士", 100, defaultWarriorattack);
        Enemy slime = new Enemy("スライムもどき",defaultslimeHP, 10);

        for(int count=0; count<10; count++){
            demoWarrior.attackWithWeaponSkill(slime);
        }

        assertEquals((defaultWarriorattack*1.5)*10, defaultslimeHP - slime.getHitPoint());
    }
}

